name: LiquidWindow
options:
  bundleIdPrefix: com.liquidwindow
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGN_STYLE: Manual
    PRODUCT_BUNDLE_IDENTIFIER: com.liquidwindow.app
targets:
  LiquidWindow:
    type: application
    platform: macOS
    sources:
      - path: Sources
      - path: Resources/Assets.xcassets
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_LSUIElement: true
        INFOPLIST_KEY_CFBundleDisplayName: LiquidWindow
        CODE_SIGN_ENTITLEMENTS: Resources/LiquidWindow.entitlements
        PRODUCT_NAME: LiquidWindow
    entitlements:
      path: Resources/LiquidWindow.entitlements
